import { Question } from "./types";



export const sampleQuestions: Question[] = [
  // ----- Multiple Choice (radio) -----
  {
    id: 1,
    question: "What does HTML stand for?",
    choices: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyperlinking Text Management Language"],
    type: "radio",
    correctText: "Hyper Text Markup Language",
  },
  {
    id: 2,
    question: "Which language runs in a web browser?",
    choices: ["Java", "C", "Python", "JavaScript"],
    type: "radio",
    correctText: "JavaScript",
  },
  {
    id: 3,
    question: "Which of these is a JavaScript framework?",
    choices: ["Laravel", "Django", "React", "Flask"],
    type: "radio",
    correctText: "React",
  },
  {
    id: 4,
    question: "What is the default port for HTTP?",
    choices: ["21", "80", "443", "8080"],
    type: "radio",
    correctText: "80",
  },
  {
    id: 5,
    question: "Which CSS property controls text size?",
    choices: ["font-style", "text-size", "font-size", "text-style"],
    type: "radio",
    correctText: "font-size",
  },
  {
    id: 6,
    question: "What does JSON stand for?",
    choices: ["JavaScript Object Notation", "Java Syntax Object Name", "JavaScript Output Name", "Joined Simple Object Notation"],
    type: "radio",
    correctText: "JavaScript Object Notation",
  },
  {
    id: 7,
    question: "Which company developed React?",
    choices: ["Google", "Facebook", "Microsoft", "Twitter"],
    type: "radio",
    correctText: "Facebook",
  },
  {
    id: 8,
    question: "Which hook is used to manage state in a React function component?",
    choices: ["useEffect", "useRef", "useState", "useMemo"],
    type: "radio",
    correctText: "useState",
  },
  {
    id: 9,
    question: "Which SQL statement is used to extract data from a database?",
    choices: ["GET", "EXTRACT", "SELECT", "PULL"],
    type: "radio",
    correctText: "SELECT",
  },
  {
    id: 10,
    question: "Which of the following is a Python web framework?",
    choices: ["Express", "Flask", "Spring", "Vue"],
    type: "radio",
    correctText: "Flask",
  },

  // ----- True or False (checkbox) -----
  {
    id: 11,
    question: "React uses a virtual DOM to improve performance.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "True",
  },
  {
    id: 12,
    question: "CSS stands for Cascading Style Syntax.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "False",
  },
  {
    id: 13,
    question: "JavaScript can be used for both frontend and backend development.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "True",
  },
  {
    id: 14,
    question: "In SQL, DELETE removes a table from the database.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "False",
  },
  {
    id: 15,
    question: "Next.js is built on top of React.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "True",
  },
  {
    id: 16,
    question: "Redux can only be used with React.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "False",
  },
  {
    id: 17,
    question: "HTML5 introduced semantic elements like <header> and <footer>.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "True",
  },
  {
    id: 18,
    question: "The 'useEffect' hook runs before rendering the component.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "False",
  },
  {
    id: 19,
    question: "MongoDB stores data in a relational format using tables and rows.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "False",
  },
  {
    id: 20,
    question: "TypeScript is a superset of JavaScript that adds static typing.",
    choices: ["True", "False"],
    type: "checkbox",
    correctText: "True",
  },

  // ----- Text Input -----
  {
    id: 21,
    question: "What is the command to initialize a new React app using Vite?",
    choices: [],
    type: "text",
    correctText: "npm create vite@latest",
  },
  {
    id: 22,
    question: "What keyword is used to declare a constant variable in JavaScript?",
    choices: [],
    type: "text",
    correctText: "const",
  },
  {
    id: 23,
    question: "In React, what hook is used to perform side effects?",
    choices: [],
    type: "text",
    correctText: "useEffect",
  },
  {
    id: 24,
    question: "Which command is used to install dependencies listed in package.json?",
    choices: [],
    type: "text",
    correctText: "npm install",
  },
  {
    id: 25,
    question: "What symbol is used to denote an array in JavaScript?",
    choices: [],
    type: "text",
    correctText: "[]",
  },
  {
    id: 26,
    question: "What method converts a JSON string into a JavaScript object?",
    choices: [],
    type: "text",
    correctText: "JSON.parse",
  },
  {
    id: 27,
    question: "What HTTP method is typically used to update data on a server?",
    choices: [],
    type: "text",
    correctText: "PUT",
  },
  {
    id: 28,
    question: "In TypeScript, what operator is used for non-null assertion?",
    choices: [],
    type: "text",
    correctText: "!",
  },
  {
    id: 29,
    question: "Which lifecycle hook in React replaces componentDidMount?",
    choices: [],
    type: "text",
    correctText: "useEffect",
  },
  {
    id: 30,
    question: "What is the file extension used for TypeScript files?",
    choices: [],
    type: "text",
    correctText: ".ts",
  },
];
